---
schild:
  endpoint: https://www.schild.ch/
  interval: 100
  maxruntime: 50

#heise:
#  endpoint: https://www.heise.de/
#  interval: 5
#  maxruntime: 50
#bestbytes:
#  endpoint: https://www.bestbytes.com/
#  interval: 10
#  alert:
#    after: 100
#nodns:
#  endpoint: http://jan:jan@127.0.0.1:8888/status
#  interval: 300
#dnserr:
#  endpoint: https://www.ca-not-resolve.this/
#  interval: 3

