language: go
go:
  - 1.8

script:
  - go get github.com/Masterminds/glide
  - glide install
  - go test -v $(glide nv)

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker-build && make docker-push;
    fi;