language: go
go:
  - 1.8
  - tip

script:
  - go get github.com/Masterminds/glide
  - glide install
  - go test -v $(glide nv)

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make build-docker
    make push-docker
    fi