language: go
go:
  - 1.8

cache:
  directories:
    - vendor

sudo: required

services:
  - docker

script:
  - go get github.com/Masterminds/glide
  - glide install
  - go test -v $(glide nv)

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker-build ;
      docker login -u=$(DOCKER_USERNAME) -p=$(DOCKER_PASSWORD) ;
      docker push foomo/petze ;
    fi;